/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.SQLException;
import javax.swing.JOptionPane;
import model.DAL;
import model.LivrosDAO;
import model.UsuarioDAO;

/**
 *
 * @author musle
 */
public class FrmManterUser extends javax.swing.JDialog {

    /**
     * Creates new form FrmCadUser
     */
    public FrmManterUser(java.awt.Frame parent, boolean modal, LivrosDAO livro, UsuarioDAO user, String operacao) {
        super(parent, modal);
        initComponents();
        this.setResizable(false);
        rootPane.setDefaultButton(btnOperacao);
        
        setUser(user);
        setOperacao(operacao);
        
        if(getOperacao().equals("Excluir"))
            operacaoDeletar();
        else if(getOperacao().equals("Editar"))
            operacaoEditar();
        else if(getOperacao().equals("Listar") || getOperacao().equals("Pesquisar"))
            operacaoVisualizar();
        
    }
    
    private UsuarioDAO user;
    private String operacao;

    public UsuarioDAO getUser() {
        return user;
    }

    public String getOperacao() {
        return operacao;
    }

    public void setOperacao(String operacao) {
        this.operacao = operacao;
    }

    public void setUser(UsuarioDAO user) {
        this.user = user;
    }
    
    private void operacaoDeletar(){
        lblOperacao.setText(getOperacao().toUpperCase() + " USUARIO");
        btnOperacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user-remove-sm.png")));
        lblTipo.setVisible(false);
        rbAdm.setVisible(false);
        rbAluno.setVisible(false);
        rbFunc.setVisible(false);
        escondeSenha();
        preencheCampos();
        camposNaoEditaveis();
    }
    
    private void operacaoEditar(){
        btnOperacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user-edit-sm.png")));
        lblOperacao.setText(getOperacao().toUpperCase() + " USUARIO");
        preencheCampos();
    }
    
    private void operacaoVisualizar(){
        btnOperacao.setVisible(false);
        rbAdm.setEnabled(false);
        rbAluno.setEnabled(false);
        rbFunc.setEnabled(false);
        escondeSenha();
        camposNaoEditaveis();
        preencheCampos();
    }
    
    private void escondeSenha(){
        txtSenha.setVisible(false);
        lblSenha.setVisible(false);
        txtSenha1.setVisible(false);
        lblSenha1.setVisible(false);
    }

    private void preencheCampos(){
        txtNome.setText(getUser().getNome());
        txtLogin.setText(getUser().getLogin());
        btnOperacao.setText(getOperacao());
        if(getUser().getTipo().equals("Adm"))
            rbAdm.setSelected(true);
        else if(getUser().getTipo().equals("Func"))
            rbFunc.setSelected(true);
        else
            rbAluno.setSelected(true);
    }
    
    private void camposNaoEditaveis(){
        txtNome.setEditable(false);
        txtLogin.setEditable(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lblOperacao = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        lblSenha1 = new javax.swing.JLabel();
        txtSenha1 = new javax.swing.JPasswordField();
        rbAdm = new javax.swing.JRadioButton();
        rbFunc = new javax.swing.JRadioButton();
        rbAluno = new javax.swing.JRadioButton();
        lblTipo = new javax.swing.JLabel();
        btnOperacao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("USUARIO");

        jLabel1.setText("Nome");

        jLabel2.setText("Login");

        lblSenha.setText("Senha");

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        lblOperacao.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblOperacao.setForeground(new java.awt.Color(255, 255, 255));
        lblOperacao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOperacao.setText("USUÁRIO");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user-config-lg.png"))); // NOI18N
        jLabel3.setToolTipText("");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOperacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblOperacao)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblSenha1.setText("Confirmar Senha");

        btnGroup.add(rbAdm);
        rbAdm.setText("Administrador");
        rbAdm.setActionCommand("Adm");

        btnGroup.add(rbFunc);
        rbFunc.setText("Funcionário");
        rbFunc.setActionCommand("Func");

        btnGroup.add(rbAluno);
        rbAluno.setSelected(true);
        rbAluno.setText("Aluno");

        lblTipo.setText("Tipo");

        btnOperacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user-insert-sm.png"))); // NOI18N
        btnOperacao.setText("Inserir");
        btnOperacao.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnOperacao.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnOperacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOperacaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblSenha)
                        .addGap(90, 90, 90)
                        .addComponent(txtSenha))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(lblSenha1)
                            .addComponent(lblTipo))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rbAdm)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbFunc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbAluno))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnOperacao)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtLogin)
                                    .addComponent(txtNome)
                                    .addComponent(txtSenha1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSenha)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSenha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSenha1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipo)
                    .addComponent(rbAdm)
                    .addComponent(rbFunc)
                    .addComponent(rbAluno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOperacao)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnOperacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOperacaoActionPerformed
        UsuarioDAO user = new UsuarioDAO();
        if(!getOperacao().equals("Inserir"))
            user.setId(getUser().getId());
        user.setNome(txtNome.getText());
        user.setLogin(txtLogin.getText());
        user.setSenha(new String (txtSenha.getPassword()).trim());
        user.setTipo(btnGroup.getSelection().getActionCommand());
        try {
            if(!confereSenha())
            mensagemSenha();
            else if(getOperacao().equals("Inserir")){
                DAL.getInstancia().insereUsuario(user);
                mensagemSucesso("Cadastro");
            }else if(getOperacao().equals("Editar")){
                DAL.getInstancia().editaUsuario(user);
                mensagemSucesso("Edição");
            }else if(getOperacao().equals("Excluir")){
                DAL.getInstancia().removeGeral(Integer.toString(user.getId()), "usuario");
                mensagemSucesso("Exclusão");
            }
            this.dispose();
        } catch (ClassNotFoundException | SQLException ex) {
            mensagemErro();
        }
    }//GEN-LAST:event_btnOperacaoActionPerformed

    private void mensagemSucesso(String operacao){
        JOptionPane.showMessageDialog(this, operacao + " de " + txtNome.getText() + " realizado com sucesso", "Aviso", JOptionPane.INFORMATION_MESSAGE);
    }
    
    private void mensagemErro(){
        JOptionPane.showMessageDialog(this, "Operação não pode ser efetuada", "Aviso", JOptionPane.WARNING_MESSAGE);
    }
    
    private void mensagemSenha(){
        JOptionPane.showMessageDialog(this, "As senhas devem ser iguais", "Aviso", JOptionPane.WARNING_MESSAGE);
    }
    
    private Boolean confereSenha(){
        String primeira = new String (txtSenha.getPassword()).trim();
        String segunda = new String (txtSenha1.getPassword()).trim();
        if(!primeira.equals(segunda))
            return false;
        else
            return true;       
    }
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmManterUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmManterUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmManterUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmManterUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmManterUser dialog = new FrmManterUser(new javax.swing.JFrame(), true, new LivrosDAO(), new UsuarioDAO(), new String());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroup;
    private javax.swing.JButton btnOperacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblOperacao;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblSenha1;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JRadioButton rbAdm;
    private javax.swing.JRadioButton rbAluno;
    private javax.swing.JRadioButton rbFunc;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtNome;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JPasswordField txtSenha1;
    // End of variables declaration//GEN-END:variables
}
