/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JFrame;
import model.UsuarioDAO;

/**
 *
 * @author musle
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        FrmLogin login = new FrmLogin(this, true);
        login.setVisible(true);
        setUsuario(login.getUsuario());
        arrumaBotoes();        
    }
    private UsuarioDAO usuario;

    private UsuarioDAO getUsuario() {
        return usuario;
    }

    private void setUsuario(UsuarioDAO usuario) {
        this.usuario = usuario;
    }
    
    private void arrumaBotoes(){
        if(!getUsuario().getTipo().equals("Adm")){
            if(getUsuario().getTipo().equals("Func")){                
                btnIncluiUser.setEnabled(false);
                btnAlteraUser.setEnabled(false);
                btnExcluiUser.setEnabled(false);
            }else{
                btnIncluiLivro.setEnabled(false);
                btnAlteraLivro.setEnabled(false);
                btnExcluiLivro.setEnabled(false);
                btnIncluiUser.setEnabled(false);
                btnAlteraUser.setEnabled(false);
                btnExcluiUser.setEnabled(false);
                btnPesquisaUser.setEnabled(false);
                btnListaUser.setEnabled(false);
                btnMultasUser.setEnabled(false);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        btnEmprestimoLivro = new javax.swing.JButton();
        btnReservaLivro = new javax.swing.JButton();
        btnIncluiLivro = new javax.swing.JButton();
        btnAlteraLivro = new javax.swing.JButton();
        btnExcluiLivro = new javax.swing.JButton();
        btnPesquisaLivro = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnListaUser = new javax.swing.JButton();
        btnMultasUser = new javax.swing.JButton();
        btnIncluiUser = new javax.swing.JButton();
        btnAlteraUser = new javax.swing.JButton();
        btnExcluiUser = new javax.swing.JButton();
        btnPesquisaUser = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BIBLIOTECA");
        setBackground(new java.awt.Color(51, 51, 51));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BIBLIOTECA");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/book-main-lg.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1))
        );

        btnEmprestimoLivro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/book-loan-lg.png"))); // NOI18N
        btnEmprestimoLivro.setText("Empréstimo");
        btnEmprestimoLivro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEmprestimoLivro.setPreferredSize(new java.awt.Dimension(100, 100));
        btnEmprestimoLivro.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnEmprestimoLivro.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEmprestimoLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmprestimoLivroActionPerformed(evt);
            }
        });

        btnReservaLivro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/book-love-lg.png"))); // NOI18N
        btnReservaLivro.setText("Reserva");
        btnReservaLivro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReservaLivro.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnReservaLivro.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnReservaLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservaLivroActionPerformed(evt);
            }
        });

        btnIncluiLivro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/book-insert-lg.png"))); // NOI18N
        btnIncluiLivro.setText("Incluir");
        btnIncluiLivro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnIncluiLivro.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnIncluiLivro.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnIncluiLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluiLivroActionPerformed(evt);
            }
        });

        btnAlteraLivro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/book-edit-lg.png"))); // NOI18N
        btnAlteraLivro.setText("Alterar");
        btnAlteraLivro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAlteraLivro.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnAlteraLivro.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAlteraLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlteraLivroActionPerformed(evt);
            }
        });

        btnExcluiLivro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/book-remove-lg.png"))); // NOI18N
        btnExcluiLivro.setText("Excluir");
        btnExcluiLivro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExcluiLivro.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnExcluiLivro.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExcluiLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluiLivroActionPerformed(evt);
            }
        });

        btnPesquisaLivro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/book-search-lg.png"))); // NOI18N
        btnPesquisaLivro.setText("Pesquisa");
        btnPesquisaLivro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPesquisaLivro.setPreferredSize(new java.awt.Dimension(100, 100));
        btnPesquisaLivro.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnPesquisaLivro.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPesquisaLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaLivroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnIncluiLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisaLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnEmprestimoLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(btnReservaLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnAlteraLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(btnExcluiLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEmprestimoLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnReservaLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPesquisaLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIncluiLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlteraLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluiLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        jTabbedPane2.addTab("Livros", jPanel3);

        btnListaUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user-info-lg.png"))); // NOI18N
        btnListaUser.setText("Listar");
        btnListaUser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnListaUser.setPreferredSize(new java.awt.Dimension(100, 100));
        btnListaUser.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnListaUser.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnListaUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaUserActionPerformed(evt);
            }
        });

        btnMultasUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user-debt-lg.png"))); // NOI18N
        btnMultasUser.setText("Multas");
        btnMultasUser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMultasUser.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnMultasUser.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMultasUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultasUserActionPerformed(evt);
            }
        });

        btnIncluiUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user-insert-lg.png"))); // NOI18N
        btnIncluiUser.setText("Incluir");
        btnIncluiUser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnIncluiUser.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnIncluiUser.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnIncluiUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluiUserActionPerformed(evt);
            }
        });

        btnAlteraUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user-edit-lg.png"))); // NOI18N
        btnAlteraUser.setText("Alterar");
        btnAlteraUser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAlteraUser.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnAlteraUser.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAlteraUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlteraUserActionPerformed(evt);
            }
        });

        btnExcluiUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user-delete-lg.png"))); // NOI18N
        btnExcluiUser.setText("Excluir");
        btnExcluiUser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExcluiUser.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnExcluiUser.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExcluiUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluiUserActionPerformed(evt);
            }
        });

        btnPesquisaUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user-search-lg.png"))); // NOI18N
        btnPesquisaUser.setText("Pesquisa");
        btnPesquisaUser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPesquisaUser.setPreferredSize(new java.awt.Dimension(100, 100));
        btnPesquisaUser.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnPesquisaUser.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPesquisaUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnIncluiUser, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisaUser, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnListaUser, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(btnMultasUser, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnAlteraUser, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(btnExcluiUser, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnListaUser, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnMultasUser, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPesquisaUser, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIncluiUser, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlteraUser, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluiUser, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        jTabbedPane2.addTab("Usuários", jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane2)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
    }//GEN-LAST:event_formWindowClosed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
    }//GEN-LAST:event_formWindowActivated

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    }//GEN-LAST:event_formWindowClosing

    private void btnPesquisaLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaLivroActionPerformed
        framePesquisaLivro("");
    }//GEN-LAST:event_btnPesquisaLivroActionPerformed

    private void btnPesquisaUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaUserActionPerformed
        framePesquisaUser("Pesquisar");
    }//GEN-LAST:event_btnPesquisaUserActionPerformed

    private void btnIncluiLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluiLivroActionPerformed
        FrmManterLivro manterLivro = new FrmManterLivro(this, rootPaneCheckingEnabled, null, usuario, "Inserir");
        manterLivro.setVisible(true);
    }//GEN-LAST:event_btnIncluiLivroActionPerformed

    private void btnAlteraLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlteraLivroActionPerformed
        framePesquisaLivro("Editar");
    }//GEN-LAST:event_btnAlteraLivroActionPerformed

    private void btnExcluiLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluiLivroActionPerformed
        framePesquisaLivro("Excluir");
    }//GEN-LAST:event_btnExcluiLivroActionPerformed

    private void btnEmprestimoLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmprestimoLivroActionPerformed
        framePesquisaEmpRes("Empréstimos");
    }//GEN-LAST:event_btnEmprestimoLivroActionPerformed

    private void btnReservaLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservaLivroActionPerformed
        framePesquisaEmpRes("Reservas");
    }//GEN-LAST:event_btnReservaLivroActionPerformed

    private void btnIncluiUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluiUserActionPerformed
        FrmManterUser manterUser = new FrmManterUser(this, rootPaneCheckingEnabled, null, usuario, "Inserir");
        manterUser.setVisible(true);
    }//GEN-LAST:event_btnIncluiUserActionPerformed

    private void btnAlteraUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlteraUserActionPerformed
        framePesquisaUser("Editar");
    }//GEN-LAST:event_btnAlteraUserActionPerformed

    private void btnExcluiUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluiUserActionPerformed
        framePesquisaUser("Excluir");
    }//GEN-LAST:event_btnExcluiUserActionPerformed

    private void btnListaUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaUserActionPerformed
        framePesquisaUser("Listar");
    }//GEN-LAST:event_btnListaUserActionPerformed

    private void btnMultasUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultasUserActionPerformed
        FrmListaMultas frameMultas = new FrmListaMultas(getUsuario(), "Empréstimo");
        frameMultas.setVisible(true);
    }//GEN-LAST:event_btnMultasUserActionPerformed

    private void framePesquisaLivro(String operacao){
        FrmPesquisaLivro pesquisaLivro = new FrmPesquisaLivro(getUsuario(), operacao);
        pesquisaLivro.setVisible(true);
    }
    
    private void framePesquisaEmpRes(String operacao){
        FrmPesquisaEmpRes pesquisaEmpRes = new FrmPesquisaEmpRes(getUsuario(), operacao);
        pesquisaEmpRes.setVisible(true);
    }
    
    private void framePesquisaUser(String operacao){
        FrmPesquisaUsuario pesquisaUser = new FrmPesquisaUsuario(getUsuario(), operacao);
        pesquisaUser.setVisible(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlteraLivro;
    private javax.swing.JButton btnAlteraUser;
    private javax.swing.JButton btnEmprestimoLivro;
    private javax.swing.JButton btnExcluiLivro;
    private javax.swing.JButton btnExcluiUser;
    private javax.swing.JButton btnIncluiLivro;
    private javax.swing.JButton btnIncluiUser;
    private javax.swing.JButton btnListaUser;
    private javax.swing.JButton btnMultasUser;
    private javax.swing.JButton btnPesquisaLivro;
    private javax.swing.JButton btnPesquisaUser;
    private javax.swing.JButton btnReservaLivro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JTabbedPane jTabbedPane2;
    // End of variables declaration//GEN-END:variables
}
