/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.DAL;
import model.UsuarioDAO;

/**
 *
 * @author musle
 */

public class FrmPesquisaUsuario extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */

    public FrmPesquisaUsuario(UsuarioDAO user, String operacao) {

        initComponents();

        setUser(user);
        setOperacao(operacao);
        
        if(getOperacao().equals("Editar") || getOperacao().equals("Excluir"))
            btnOperacao.setText(getOperacao());
        else
            btnOperacao.setText("Visualizar");
        
        if(getOperacao().equals("Listar")){
            lblUsuarios.setText("LISTAR USUÁRIOS");
            btnPesquisaUser.setVisible(false);
            txtPesquisaUser.setVisible(false);
            rdLogin.setVisible(false);
            rdNome.setVisible(false);
            rdTipo.setVisible(false);
        }

        ajustaTamanhoColuna();

        atualizaTableUser("", "nome");

    }

    private UsuarioDAO user;
    private String operacao;

    public UsuarioDAO getUser() {
        return user;
    }

    public void setUser(UsuarioDAO user) {
        this.user = user;
    }

    public String getOperacao() {
        return operacao;
    }

    public void setOperacao(String operacao) {
        this.operacao = operacao;
    }

    /**

     * This method is called from within the constructor to initialize the form.

     * WARNING: Do NOT modify this code. The content of this method is always

     * regenerated by the Form Editor.

     */

    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblUsuarios = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        txtPesquisaUser = new javax.swing.JTextField();
        btnPesquisaUser = new javax.swing.JButton();
        btnOperacao = new javax.swing.JButton();
        rdNome = new javax.swing.JRadioButton();
        rdLogin = new javax.swing.JRadioButton();
        rdTipo = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PESQUISA");
        setBackground(new java.awt.Color(51, 51, 51));
        setPreferredSize(null);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        lblUsuarios.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsuarios.setText("PESQUISA USUÁRIOS");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user-search-lg.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUsuarios)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Usuário", "Login", "Tipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblUsuarios.setMaximumSize(new java.awt.Dimension(300, 160));
        tblUsuarios.setMinimumSize(new java.awt.Dimension(300, 160));
        jScrollPane1.setViewportView(tblUsuarios);

        btnPesquisaUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn-search-es.png"))); // NOI18N
        btnPesquisaUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaUserActionPerformed(evt);
            }
        });

        btnOperacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/book-view-sm.png"))); // NOI18N
        btnOperacao.setText("Operação");
        btnOperacao.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnOperacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOperacaoActionPerformed(evt);
            }
        });

        btnGroup.add(rdNome);
        rdNome.setSelected(true);
        rdNome.setText("Nome");
        rdNome.setActionCommand("nome");

        btnGroup.add(rdLogin);
        rdLogin.setText("Login");
        rdLogin.setActionCommand("login");

        btnGroup.add(rdTipo);
        rdTipo.setText("Tipo");
        rdTipo.setActionCommand("tipo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnOperacao)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(txtPesquisaUser, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnPesquisaUser, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(rdNome)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(rdLogin)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(rdTipo))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPesquisaUser, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(txtPesquisaUser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdNome)
                    .addComponent(rdLogin)
                    .addComponent(rdTipo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOperacao)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisaUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaUserActionPerformed
        atualizaTableUser(txtPesquisaUser.getText(), btnGroup.getSelection().getActionCommand());
    }//GEN-LAST:event_btnPesquisaUserActionPerformed

    private void btnOperacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOperacaoActionPerformed
        if(tblUsuarios.getSelectedRowCount() > 1){
            JOptionPane.showMessageDialog(this, "Selecione apenas um usuário de cada vez para visualização", "Aviso", JOptionPane.WARNING_MESSAGE);
        }else if(tblUsuarios.getSelectedRowCount() < 1){
            JOptionPane.showMessageDialog(this, "Selecione no mínimo um usuário para visualização", "Aviso", JOptionPane.WARNING_MESSAGE);
        }else{
            FrmManterUser manterUser = new FrmManterUser(this, rootPaneCheckingEnabled, null, (UsuarioDAO)tblUsuarios.getValueAt(tblUsuarios.getSelectedRow(), 0), getOperacao());
            manterUser.setVisible(true);
        }
        atualizaTableUser("", "nome");
        
    }//GEN-LAST:event_btnOperacaoActionPerformed

    private void mensagemErro(){
        JOptionPane.showMessageDialog(this, "Operação não pode ser efetuada", "Aviso", JOptionPane.WARNING_MESSAGE);
    }

    private void ajustaTamanhoColuna(){
        tblUsuarios.getColumnModel().getColumn(0).setPreferredWidth(100);
        tblUsuarios.getColumnModel().getColumn(1).setPreferredWidth(225);
        tblUsuarios.getColumnModel().getColumn(2).setPreferredWidth(225);
    }

    private void atualizaTableUser(String pesquisa, String tipo){        
        try {
            ((javax.swing.table.DefaultTableModel) tblUsuarios.getModel()).setRowCount(0);
            ArrayList<UsuarioDAO> lstUsuarios = DAL.getInstancia().retornaUser(pesquisa, tipo);
            Integer row = 0;
            if(lstUsuarios.size() > 0){
                ((javax.swing.table.DefaultTableModel) tblUsuarios.getModel()).setRowCount(lstUsuarios.size());
                for (UsuarioDAO user : lstUsuarios) {
                    tblUsuarios.getModel().setValueAt(user, row, 0);
                    tblUsuarios.getModel().setValueAt(user.getLogin(), row, 1);
                    tblUsuarios.getModel().setValueAt(user.getTipo(), row, 2);
                    row++;
                }
            }else{
                ((javax.swing.table.DefaultTableModel) tblUsuarios.getModel()).setRowCount(1);
                tblUsuarios.getModel().setValueAt("Nenhuma linha encontrada", row, 0);   
            }
        } catch (ClassNotFoundException | SQLException ex) {
            mensagemErro();
        }
    }

    /**

     * @param args the command line arguments

     */

    public static void main(String args[]) {

        /* Set the Nimbus look and feel */

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">

        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.

         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 

         */

        try {

            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {

                if ("Nimbus".equals(info.getName())) {

                    javax.swing.UIManager.setLookAndFeel(info.getClassName());

                    break;

                }

            }

        } catch (ClassNotFoundException ex) {

            java.util.logging.Logger.getLogger(FrmPesquisaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {

            java.util.logging.Logger.getLogger(FrmPesquisaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {

            java.util.logging.Logger.getLogger(FrmPesquisaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {

            java.util.logging.Logger.getLogger(FrmPesquisaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        }

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>



        /* Create and display the form */

        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {

                new FrmPesquisaUsuario(new UsuarioDAO(), new String()).setVisible(true);

            }

        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroup;
    private javax.swing.JButton btnOperacao;
    private javax.swing.JButton btnPesquisaUser;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblUsuarios;
    private javax.swing.JRadioButton rdLogin;
    private javax.swing.JRadioButton rdNome;
    private javax.swing.JRadioButton rdTipo;
    private javax.swing.JTable tblUsuarios;
    private javax.swing.JTextField txtPesquisaUser;
    // End of variables declaration//GEN-END:variables

}

